// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCslOVHFkY3JmEAbsLZVHrmD09_FhKmoyA',
    appId: '1:152751015910:web:822f3d4f3544948889b827',
    messagingSenderId: '152751015910',
    projectId: 'noteswebapp-7ab1e',
    authDomain: 'noteswebapp-7ab1e.firebaseapp.com',
    storageBucket: 'noteswebapp-7ab1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslOVHFkY3JmEAbsLZVHrmD09_FhKmoyA',
    appId: '1:152751015910:android:your_android_app_id',
    messagingSenderId: '152751015910',
    projectId: 'noteswebapp-7ab1e',
    storageBucket: 'noteswebapp-7ab1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslOVHFkY3JmEAbsLZVHrmD09_FhKmoyA',
    appId: '1:152751015910:ios:your_ios_app_id',
    messagingSenderId: '152751015910',
    projectId: 'noteswebapp-7ab1e',
    storageBucket: 'noteswebapp-7ab1e.firebasestorage.app',
    iosBundleId: 'com.example.googleKeepCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCslOVHFkY3JmEAbsLZVHrmD09_FhKmoyA',
    appId: '1:152751015910:ios:your_macos_app_id',
    messagingSenderId: '152751015910',
    projectId: 'noteswebapp-7ab1e',
    storageBucket: 'noteswebapp-7ab1e.firebasestorage.app',
    iosBundleId: 'com.example.googleKeepCloneFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCslOVHFkY3JmEAbsLZVHrmD09_FhKmoyA',
    appId: '1:152751015910:web:822f3d4f3544948889b827',
    messagingSenderId: '152751015910',
    projectId: 'noteswebapp-7ab1e',
    authDomain: 'noteswebapp-7ab1e.firebaseapp.com',
    storageBucket: 'noteswebapp-7ab1e.firebasestorage.app',
  );
}
